spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    aws:
      credentials:
        access-key: ${SPRING_AWS_KEY}
        secret-key: ${SPRING_AWS_SECRET}
      region:
        static: ap-northeast-1
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 1c2b0d7f4f4d1d
    password: 76f7b23714f29f
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework: INFO
  file:
    name: /var/log/springboot/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

app:
  version: 1.0.0

jwt:
  secret: 2JY4mcOkbKHGRFqCjF5eVzUnm7whbZsCHmGMk/f3Nh6OTMWrQfh4gng58jjCqHgMtApPW7QZVQmuSkaLCe7sKw==
  access-token-validity: 3600000 # 1小時 (單位是毫秒)

cloud:
  aws:
    region:
      static: ap-northeast-1
    stack:
      auto: false
  sqs:
    queue-name: mfa-email-queue
    endpoint: https://sqs.ap-northeast-1.amazonaws.com/876997124426/mfa-email-queue
